version: "3.8"
services:
  db:
    container_name: db
    image: postgres:10
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
     - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
  web:
    container_name: web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
    - DATABASE_URL=postgres://postgres:password@db:5432/postgres
volumes:
  dbdata: